/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        display: ["Inter", "PingFang SC", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Microsoft YaHei", "sans-serif"],
        body: ["PingFang SC", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Microsoft YaHei", "sans-serif"],
        mono: ["Menlo", "Consolas", "monospace"],
      },
      fontSize: {
        eyebrow: ["11px", { lineHeight: "1.4", letterSpacing: "0.08em", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.5" }],
      },
      colors: {
        feiyu: {
          bg: "var(--feiyu-bg)",
          "bg-hover": "var(--feiyu-bg-hover)",
          card: "var(--feiyu-card)",
          surface: "var(--feiyu-surface)",
          "surface-dim": "var(--feiyu-surface-dim)",
          "surface-container": "var(--feiyu-surface-container)",
          "surface-container-high": "var(--feiyu-surface-container-high)",
          "surface-container-highest": "var(--feiyu-surface-container-highest)",
          sidebar: "var(--feiyu-sidebar)",
          "sidebar-hover": "var(--feiyu-sidebar-hover)",
          "sidebar-active": "var(--feiyu-sidebar-active)",
          primary: "var(--feiyu-primary)",
          "primary-hover": "var(--feiyu-primary-hover)",
          "primary-light": "var(--feiyu-primary-light)",
          "primary-soft": "var(--feiyu-primary-soft)",
          border: "var(--feiyu-border)",
          "border-light": "var(--feiyu-border-light)",
          text: "var(--feiyu-text)",
          "text-secondary": "var(--feiyu-text-secondary)",
          "text-muted": "var(--feiyu-text-muted)",
          "bubble-own": "var(--feiyu-bubble-own)",
          "bubble-other": "var(--feiyu-bubble-other)",
          success: "var(--feiyu-success)",
          warning: "var(--feiyu-warning)",
          danger: "var(--feiyu-danger)",
          info: "var(--feiyu-info)",
        },
      },
      boxShadow: {
        "feiyu-1": "0 1px 2px 0 rgba(31,35,41,0.06)",
        "feiyu-2": "0 2px 4px 0 rgba(31,35,41,0.08)",
        "feiyu-3": "0 4px 8px 0 rgba(31,35,41,0.10)",
        "feiyu-4": "0 8px 16px 0 rgba(31,35,41,0.12)",
        "feiyu-5": "0 12px 24px 0 rgba(31,35,41,0.16)",
      },
      borderRadius: {
        "feiyu-sm": "4px",
        "feiyu-md": "6px",
        "feiyu-lg": "8px",
        "feiyu-xl": "12px",
        "feiyu-pill": "9999px",
      },
    },
  },
  plugins: [],
};
